/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {};

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('primevue/button')['default']
    ChatChatBox: typeof import('../modules/chat/components/ChatBox.vue')['default']
    ChatChatList: typeof import('../modules/chat/components/ChatList.vue')['default']
    ChatSidebar: typeof import('../modules/chat/components/Sidebar.vue')['default']
    ContextMenu: typeof import('primevue/contextmenu')['default']
    LayoutContent: typeof import('./../components/layout/Content.vue')['default']
    LayoutFooter: typeof import('./../components/layout/Footer.vue')['default']
    LayoutHeader: typeof import('./../components/layout/Header.vue')['default']
    LayoutSidebar: typeof import('./../components/layout/Sidebar.vue')['default']
    LayoutView: typeof import('./../components/layout/View.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('primevue/sidebar')['default']
    Tab: typeof import('primevue/tab')['default']
    TabList: typeof import('primevue/tablist')['default']
    TabPanel: typeof import('primevue/tabpanel')['default']
    TabPanels: typeof import('primevue/tabpanels')['default']
    Tabs: typeof import('primevue/tabs')['default']
    Textarea: typeof import('primevue/textarea')['default']
    Tree: typeof import('primevue/tree')['default']
  }
  export interface ComponentCustomProperties {
    Tooltip: typeof import('primevue/tooltip')['default']
  }
}
